DROP SEQUENCE ORDDETAIL_ODNO_SEQ;

CREATE SEQUENCE ORDDETAIL_ODNO_SEQ
INCREMENT BY 1
START WITH 1;

--예제
INSERT INTO ORDDETAIL(ODNO,ODQTY,ODPRICE,ONO,PNO)
VALUES(ORDDETAIL_ODNO_SEQ.NEXTVAL, 4, 15000, 1, NULL);

UPDATE ORDDETAIL
SET ODQTY=3 ,ODPRICE= 12000,ONO=NULL,PNO=NULL
WHERE ODNO = 1;

DELETE FROM orddetail WHERE ODNO=1;

SELECT * FROM orddetail;
COMMIT;

--사용문법
INSERT INTO ORDDETAIL(ODNO,ODQTY,ODPRICE,ONO,PNO)
VALUES(ORDDETAIL_ODNO_SEQ.NEXTVAL, ?, ?, ?, ?);

UPDATE ORDDETAIL
SET ODQTY=? ,ODPRICE= ?,ONO=?,PNO=?
WHERE ODNO = ?;

DELETE FROM orddetail WHERE ODNO=?;

SELECT * FROM orddetail;




